### PR TITLE
Fix two potential problems

### PR DESCRIPTION
**Pull request by wasedaigo**
As this repository looks more active, let me PR here.

- Assigning bound.x/bound.y as frame.x/frame.y sounds wrong to me
- It was passing bound.x as y-coordinate, that sounds wrong as well

I fixed spacing too.

### CODE REVIEW

**Comment by avishayil** [comment]
Thanks! I'll test it and merge if applicable...
This repository needs more work, but it works well - at least the `PublisherBanner` component.
I'd be happy if more people could help on the other components as well.

**Comment by wasedaigo** [comment]
Thanks for taking a look.
If the original author does not come back, we can make a new npm module I guess. 

What is your thoughts on the rewardAds branch? As I need that feature, I am considering of merging it. Do you think it is better for me to work on my fork, or be a collaborator on this repo?

**Comment by avishayil** [comment]
Yeah, PR here and i'll make a new module.

**Comment by wasedaigo** [comment]
ok

**Comment by avishayil** [comment]
@wasedaigo That makes sense, but since I don't have much understanding on iOS (I'm coming from the Android side), i'll go by your instructions.

**Pull request merged**
